/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author ether
 */
public class ActualizarExamen extends javax.swing.JPanel {

    /**
     * Creates new form ACTUALIZAR_EXAMEN
     */
    public ActualizarExamen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formularioP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cedulaExamen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fechaExamen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        escuelaExamen = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        puntajeExamen = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        puntajeFigurasExamen = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nombreInstructor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        indicadorPrueba = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        formularioP.setBackground(new java.awt.Color(0, 51, 51));
        formularioP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        formularioP.setLayout(new java.awt.GridLayout(7, 2));

        jLabel3.setText("Cédula");
        formularioP.add(jLabel3);
        formularioP.add(cedulaExamen);

        jLabel4.setText("Fecha de presentación");
        formularioP.add(jLabel4);

        fechaExamen.setText("dd/mm/aa");
        formularioP.add(fechaExamen);

        jLabel13.setText("Escuela");
        formularioP.add(jLabel13);

        escuelaExamen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "WTF", "ITF" }));
        formularioP.add(escuelaExamen);

        jLabel14.setText("Puntaje de combate");
        formularioP.add(jLabel14);
        formularioP.add(puntajeExamen);

        jLabel15.setText("Puntaje de figuras");
        formularioP.add(jLabel15);
        formularioP.add(puntajeFigurasExamen);

        jLabel16.setText("Nombre del instructor");
        formularioP.add(jLabel16);
        formularioP.add(nombreInstructor);

        jLabel17.setText("Indicador de prueba");
        formularioP.add(jLabel17);

        indicadorPrueba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A", "N" }));
        formularioP.add(indicadorPrueba);

        jPanel1.add(formularioP, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setText("Actualize un examen");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jLabel10.setText("                         ");
        jPanel1.add(jLabel10, java.awt.BorderLayout.WEST);

        jLabel11.setText("                         ");
        jPanel1.add(jLabel11, java.awt.BorderLayout.EAST);

        jLabel12.setText(" ");
        jPanel1.add(jLabel12, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulaExamen;
    private javax.swing.JComboBox<String> escuelaExamen;
    private javax.swing.JTextField fechaExamen;
    private javax.swing.JPanel formularioP;
    private javax.swing.JComboBox<String> indicadorPrueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nombreInstructor;
    private javax.swing.JTextField puntajeExamen;
    private javax.swing.JTextField puntajeFigurasExamen;
    // End of variables declaration//GEN-END:variables
}
