/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Modelo.Director;
import Modelo.Liga;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ether
 */
public class CrearLiga extends javax.swing.JPanel {

    /**
     * Creates new form CREAR_LIGA
     */
    public CrearLiga() {
        initComponents();
        ((JTextField) this.JDatefechaafiliacion.getDateEditor()).setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validacion_dan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        formulario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JTextpersoneriajuridica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JDatefechaafiliacion = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        JComboescuela = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JTextciudadsede = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTextcedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTextnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JCombogrado = new javax.swing.JComboBox<>();
        panelDAN = new javax.swing.JPanel();
        check_si = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        check_no = new javax.swing.JCheckBox();
        JCombodan = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        btn_crear = new javax.swing.JButton();
        JTextidentificacionfederacion = new javax.swing.JTextField();
        titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        formulario.setBackground(new java.awt.Color(0, 0, 0));
        formulario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personeria Juridica");

        JTextpersoneriajuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextpersoneriajuridicaActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de Afiliación");

        JDatefechaafiliacion.setDateFormatString("yyyy/MM/d");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Escuela");

        JComboescuela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "WTF", "ITF" }));
        JComboescuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboescuelaActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ciudad de Sede");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cedula del Director");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre del Director");

        JTextnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextnombreActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Grado del Director");

        JCombogrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Blanco", "Amarillo", "Verde", "Azul", "Rojo", "Negro" }));

        panelDAN.setBackground(new java.awt.Color(0, 0, 0));

        check_si.setBackground(new java.awt.Color(0, 0, 0));
        validacion_dan.add(check_si);
        check_si.setForeground(new java.awt.Color(255, 255, 255));
        check_si.setText("Si");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Numero de DAN");

        check_no.setBackground(new java.awt.Color(0, 0, 0));
        validacion_dan.add(check_no);
        check_no.setForeground(new java.awt.Color(255, 255, 255));
        check_no.setText("No");

        javax.swing.GroupLayout panelDANLayout = new javax.swing.GroupLayout(panelDAN);
        panelDAN.setLayout(panelDANLayout);
        panelDANLayout.setHorizontalGroup(
            panelDANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDANLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(check_si)
                .addGap(18, 18, 18)
                .addComponent(check_no)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDANLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelDANLayout.setVerticalGroup(
            panelDANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDANLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_si)
                    .addComponent(check_no)))
        );

        JCombodan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Identificación de la federación");

        btn_crear.setText("Crear");
        btn_crear.setToolTipText("");
        btn_crear.setBorderPainted(false);
        btn_crear.setDefaultCapable(false);
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formularioLayout = new javax.swing.GroupLayout(formulario);
        formulario.setLayout(formularioLayout);
        formularioLayout.setHorizontalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioLayout.createSequentialGroup()
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formularioLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(panelDAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13))
                        .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formularioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JDatefechaafiliacion, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(JTextpersoneriajuridica, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(JComboescuela, 0, 210, Short.MAX_VALUE)
                                    .addComponent(JTextciudadsede, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(JTextcedula, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(JTextnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(JCombogrado, 0, 210, Short.MAX_VALUE)
                                    .addComponent(JCombodan, 0, 210, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(JTextidentificacionfederacion, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        formularioLayout.setVerticalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioLayout.createSequentialGroup()
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextpersoneriajuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JDatefechaafiliacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboescuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextciudadsede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCombogrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCombodan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JTextidentificacionfederacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btn_crear)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel1.add(formulario, java.awt.BorderLayout.CENTER);

        titulo.setBackground(new java.awt.Color(153, 153, 0));
        titulo.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear liga");
        titulo.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel14.setText("          ");
        titulo.add(jLabel14, java.awt.BorderLayout.LINE_END);

        jLabel15.setText("          ");
        titulo.add(jLabel15, java.awt.BorderLayout.LINE_START);

        jLabel16.setText(" ");
        titulo.add(jLabel16, java.awt.BorderLayout.PAGE_START);

        jLabel17.setText(" ");
        titulo.add(jLabel17, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(titulo, java.awt.BorderLayout.PAGE_START);

        jLabel10.setText("          ");
        jPanel1.add(jLabel10, java.awt.BorderLayout.LINE_END);

        jLabel11.setText("          ");
        jPanel1.add(jLabel11, java.awt.BorderLayout.LINE_START);

        jLabel12.setText(" ");
        jPanel1.add(jLabel12, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void JTextpersoneriajuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextpersoneriajuridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextpersoneriajuridicaActionPerformed

    private void JTextnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextnombreActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        String error = "";
        //Declaracion de variables liga
        int personeriaJuridica = 0;
        try{
            personeriaJuridica = Integer.parseInt(JTextpersoneriajuridica.getText());
        } catch(NumberFormatException e){
            error += "El campo personeria juridica debe ser un numero entero y menor a 2147483647\n";
        }
        
        String fechaAfiliacion = ((JTextField)JDatefechaafiliacion.getDateEditor().getUiComponent()).getText();
        if(fechaAfiliacion.isEmpty()){
            error += "Debe ingresar la fecha de afiliacion\n";
        }
        String escuela = JComboescuela.getSelectedItem().toString();
        if(escuela.equals("Seleccionar")){
            error += "Debe seleccionar una escuela\n";
        }
        String ciudadSede = JTextciudadsede.getText();
        if(ciudadSede.isEmpty()){
            error += "El campo ciudad de sede no puede estar vacio\n";
        }
        String identificacionFederacion = JTextidentificacionfederacion.getText();
        if(identificacionFederacion.isEmpty()){
            error += "El campo identificacion de la federacion no puede estar vacio\n";
        }
        
        //Declaracion de variables director
        String cedulaDirector = JTextcedula.getText();
        if(cedulaDirector.isEmpty()){
            error += "El campo cedula del director no puede estar vacio\n";
        }
        String nombreDirector = JTextnombre.getText();
        if(nombreDirector.isEmpty()){
            error += "El campo nombre de director no puede estar vacio\n";
        }
        String gradoDirector = JCombogrado.getSelectedItem().toString();
        if(gradoDirector.equals("Seleccionar")){
            error += "Debe seleccionar un grado para el director\n";
        }
        int danDirector = 0;
        
        
        if(check_si.isSelected() && gradoDirector.equals("Negro")){
            try{
                danDirector = Integer.parseInt(JCombodan.getSelectedItem().toString());
            } catch(Exception e){
                error += "Debe seleccionar un numero de DAN para el director\n";
            }
        } else if(check_si.isSelected() && !gradoDirector.equals("Negro")){
            error += "El director debe tener el grado Negro para tener un DAN\n";
        }
        
        if(!error.isEmpty()){
            JOptionPane.showMessageDialog(null, error, "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //Creacion de objeto liga y creacion de query para crear liga
        Liga liga = new Liga(personeriaJuridica, fechaAfiliacion, escuela, ciudadSede, identificacionFederacion);
        String queryLiga = "insert into LIGAS(personeria_juridica,  fecha_afiliacion, escuela, ciudad_sede, numero_identificacion_federacion, numero_cedula_director) values (?,?,?,?,?,?)";
        //Creacion de objeto director y creacion de query para crear director
        Director director = new Director(cedulaDirector, nombreDirector, gradoDirector, danDirector);
        String queryDirector = "insert into DIRECTORES_DE_LIGAS(cedula, nombre, grado, numero_dan) values (?,?,?,?)";
        try{
            //Ingreso de datos para crear director en la DB
            
            //Ingreso de datos para crear liga en la DB
            PreparedStatement psLiga = Principal.db.prepareStatement(queryLiga);
            psLiga.setInt(1, liga.getPersoneriaJuridica());
            psLiga.setString(2, liga.getFechaAfiliacion());
            psLiga.setString(3, liga.getEscuela());
            psLiga.setString(4, liga.getCiudadSede());
            psLiga.setString(5, liga.getIdentificacionFederacion());
            PreparedStatement psDirector = Principal.db.prepareStatement(queryDirector);
            psDirector.setString(1, director.getCedula());
            psDirector.setString(2, director.getNombre());
            psDirector.setString(3, director.getGrado());
            if(danDirector > 0){
                psDirector.setInt(4, director.getNumeroDan());
            }
            else{
                psDirector.setString(4, null);
            }
            psDirector.executeUpdate();
            psLiga.setString(6, director.getCedula());
            psLiga.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Liga creada", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sqle){
            JOptionPane.showMessageDialog(null, sqle.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_crearActionPerformed

    private void JComboescuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboescuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboescuelaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCombodan;
    private javax.swing.JComboBox<String> JComboescuela;
    private javax.swing.JComboBox<String> JCombogrado;
    private com.toedter.calendar.JDateChooser JDatefechaafiliacion;
    private javax.swing.JTextField JTextcedula;
    private javax.swing.JTextField JTextciudadsede;
    private javax.swing.JTextField JTextidentificacionfederacion;
    private javax.swing.JTextField JTextnombre;
    private javax.swing.JTextField JTextpersoneriajuridica;
    private javax.swing.JButton btn_crear;
    private javax.swing.JCheckBox check_no;
    private javax.swing.JCheckBox check_si;
    private javax.swing.JPanel formulario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDAN;
    private javax.swing.JPanel titulo;
    private javax.swing.ButtonGroup validacion_dan;
    // End of variables declaration//GEN-END:variables
}
