/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Modelo.Director;
import Modelo.Liga;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ether
 */
public class CrearLiga extends javax.swing.JPanel {

    /**
     * Creates new form CREAR_LIGA
     */
    public CrearLiga() {
        initComponents();
        ((JTextField) this.JDatefechaafiliacion.getDateEditor()).setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JTextpersoneriajuridica = new javax.swing.JTextField();
        JComboescuela = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        JDatefechaafiliacion = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTextciudadsede = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTextcedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTextnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JCombogrado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        DAN_director = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel12.setText(" ");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridLayout(8, 2));

        jLabel2.setText("Personeria Juridica");
        jPanel4.add(jLabel2);

        JTextpersoneriajuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextpersoneriajuridicaActionPerformed(evt);
            }
        });
        jPanel4.add(JTextpersoneriajuridica);

        JComboescuela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "WTF", "ITF" }));
        jPanel4.add(JComboescuela);

        jLabel3.setText("Fecha de Afiliación");
        jPanel4.add(jLabel3);

        JDatefechaafiliacion.setDateFormatString("yyyy/MM/d ");
        jPanel4.add(JDatefechaafiliacion);

        jLabel4.setText("Escuela");
        jPanel4.add(jLabel4);

        jLabel5.setText("Ciudad de Sede");
        jPanel4.add(jLabel5);
        jPanel4.add(JTextciudadsede);

        jLabel6.setText("Cedula del Director");
        jPanel4.add(jLabel6);
        jPanel4.add(JTextcedula);

        jLabel7.setText("Nombre del Director");
        jPanel4.add(jLabel7);

        JTextnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextnombreActionPerformed(evt);
            }
        });
        jPanel4.add(JTextnombre);

        jLabel8.setText("Grado del Director");
        jPanel4.add(jLabel8);

        JCombogrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Blanco", "Amarillo", "Verde", "Azul", "Rojo", "Negro" }));
        jPanel4.add(JCombogrado);

        jLabel9.setText("DAN Director (Si tiene)");
        jPanel4.add(jLabel9);

        DAN_director.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel4.add(DAN_director);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(153, 153, 0));

        jLabel1.setText("CREAR LIGA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jLabel10.setText("                         ");
        jPanel1.add(jLabel10, java.awt.BorderLayout.LINE_END);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTextpersoneriajuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextpersoneriajuridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextpersoneriajuridicaActionPerformed

    private void JTextnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextnombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        //Declaracion de variables liga
        String personeriaJuridica = JTextpersoneriajuridica.getText();
        String fechaAfiliacion = ((JTextField)JDatefechaafiliacion.getDateEditor().getUiComponent()).getText();
        String escuela = JComboescuela.getSelectedItem().toString();
        String ciudadSede = JTextciudadsede.getText();
        //Declaracion de variables director
        String cedulaDirector = JTextcedula.getText();
        String nombreDirector = JTextnombre.getText();
        String gradoDirector = JCombogrado.getSelectedItem().toString();
        //Creacion de objeto liga y creacion de query para crear liga
        Liga liga = new Liga(personeriaJuridica, fechaAfiliacion, escuela, ciudadSede);
        String queryLiga = "insert into LIGA(personeria_juridica,  fecha_afiliacion, escuela, ciudad_sede, numero_identificacion_federacion) values (?,?,?,?,?)";
        //Creacion de objeto director y creacion de query para crear director
        Director director = new Director(cedulaDirector, nombreDirector, gradoDirector);
        String queryDirector = "insert into Director(cedula, nombre, grado, numero_dan, personeria_juridica_liga) values (?,?,?,?,?)";
        try{
            //Ingreso de datos para crear liga en la DB
            PreparedStatement psLiga = Principal.db.prepareStatement(queryLiga);
            psLiga.setString(1, liga.getPersoneriaJuridica());
            psLiga.setString(2, liga.getFechaAfiliacion());
            psLiga.setString(3, liga.getEscuela());
            psLiga.setString(4, liga.getCiudadSede());
            psLiga.setString(5, liga.getPersoneriaJuridica());
            psLiga.executeUpdate();
            //Ingreso de datos para crear director en la DB
            PreparedStatement psDirector = Principal.db.prepareStatement(queryDirector);
            psDirector.setString(1, director.getCedula());
            psDirector.setString(2, director.getNombre());
            psDirector.setString(3, director.getGrado());
            //psDirector.setString(4, director.getNumeroDan());
            psDirector.setString(5, liga.getPersoneriaJuridica());
            psDirector.executeUpdate();
            JOptionPane.showMessageDialog(this, "Datos ingresados", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sqle){
            System.out.println(sqle);
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DAN_director;
    private javax.swing.JComboBox<String> JComboescuela;
    private javax.swing.JComboBox<String> JCombogrado;
    private com.toedter.calendar.JDateChooser JDatefechaafiliacion;
    private javax.swing.JTextField JTextcedula;
    private javax.swing.JTextField JTextciudadsede;
    private javax.swing.JTextField JTextnombre;
    private javax.swing.JTextField JTextpersoneriajuridica;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
