/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author ether
 */
public class InscribirParticipante extends javax.swing.JPanel {

    /**
     * Creates new form INSCRIBIR_PARTICIPANTE
     */
    public InscribirParticipante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        formularioP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        seleccionarLiga = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cedulaParticipante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombreParticipante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        apellidoParticipante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fechaNacimiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fechaIngreso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel12.setText("Inscriba a un participante");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel1.setText("                         ");
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jLabel2.setText(" ");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jLabel3.setText("                         ");
        jPanel1.add(jLabel3, java.awt.BorderLayout.LINE_START);

        formularioP.setBackground(new java.awt.Color(0, 51, 51));
        formularioP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        formularioP.setLayout(new java.awt.GridLayout(8, 2));

        jLabel4.setText("Seleccione Liga");
        formularioP.add(jLabel4);

        seleccionarLiga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "No hay" }));
        formularioP.add(seleccionarLiga);

        jLabel5.setText("Cédula");
        formularioP.add(jLabel5);

        cedulaParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaParticipanteActionPerformed(evt);
            }
        });
        formularioP.add(cedulaParticipante);

        jLabel6.setText("Nombre");
        formularioP.add(jLabel6);
        formularioP.add(nombreParticipante);

        jLabel7.setText("Apellido");
        formularioP.add(jLabel7);
        formularioP.add(apellidoParticipante);

        jLabel8.setText("Fecha de Nacimiento");
        formularioP.add(jLabel8);

        fechaNacimiento.setText("dd/mm/aa");
        fechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacimientoActionPerformed(evt);
            }
        });
        formularioP.add(fechaNacimiento);

        jLabel9.setText("Fecha de Ingreso");
        formularioP.add(jLabel9);

        fechaIngreso.setText("dd/mm/aa");
        formularioP.add(fechaIngreso);

        jLabel10.setText("Nacionalidad");
        formularioP.add(jLabel10);
        formularioP.add(nacionalidad);

        jLabel11.setText("Peso (Kg)");
        formularioP.add(jLabel11);

        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });
        formularioP.add(peso);

        jPanel1.add(formularioP, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cedulaParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaParticipanteActionPerformed

    private void fechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacimientoActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoParticipante;
    private javax.swing.JTextField cedulaParticipante;
    private javax.swing.JTextField fechaIngreso;
    private javax.swing.JTextField fechaNacimiento;
    private javax.swing.JPanel formularioP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JTextField nombreParticipante;
    private javax.swing.JTextField peso;
    private javax.swing.JComboBox<String> seleccionarLiga;
    // End of variables declaration//GEN-END:variables
}
