/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Modelo.Practicante;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ether
 */
public class InscribirPracticante extends javax.swing.JPanel {

    /**
     * Creates new form INSCRIBIR_PARTICIPANTE
     */
    public InscribirPracticante() {
        initComponents();
        ((JTextField) this.JDatefechanacimiento.getDateEditor()).setEditable(false);
        ((JTextField) this.JDatefechaingreso.getDateEditor()).setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        formularioP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JTextliga = new javax.swing.JTextField();
        btn_buscarLiga = new javax.swing.JButton();
        JComboBoxliga = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JTextcedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTextnombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTextapellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JDatefechanacimiento = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        JDatefechaingreso = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        JTextnacionalidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JTextpeso = new javax.swing.JTextField();
        btn_inscribir = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel12.setText("Inscriba a un participante");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel1.setText("                         ");
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jLabel2.setText(" ");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jLabel3.setText("                         ");
        jPanel1.add(jLabel3, java.awt.BorderLayout.LINE_START);

        formularioP.setBackground(new java.awt.Color(0, 0, 0));
        formularioP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        formularioP.setLayout(new java.awt.GridLayout(9, 2));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Liga");
        formularioP.add(jLabel4);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        JTextliga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextligaActionPerformed(evt);
            }
        });

        btn_buscarLiga.setText("Buscar");
        btn_buscarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarLigaActionPerformed(evt);
            }
        });

        JComboBoxliga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        JComboBoxliga.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JTextliga, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscarLiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JComboBoxliga, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextliga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarLiga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JComboBoxliga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formularioP.add(jPanel3);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cédula");
        formularioP.add(jLabel5);

        JTextcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextcedulaActionPerformed(evt);
            }
        });
        formularioP.add(JTextcedula);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");
        formularioP.add(jLabel6);
        formularioP.add(JTextnombre);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido");
        formularioP.add(jLabel7);
        formularioP.add(JTextapellido);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de Nacimiento");
        formularioP.add(jLabel8);

        JDatefechanacimiento.setDateFormatString("yyyy/MM/d");
        formularioP.add(JDatefechanacimiento);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de Ingreso");
        formularioP.add(jLabel9);

        JDatefechaingreso.setDateFormatString("yyyy/MM/d");
        formularioP.add(JDatefechaingreso);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nacionalidad");
        formularioP.add(jLabel10);
        formularioP.add(JTextnacionalidad);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Peso (Kg)");
        formularioP.add(jLabel11);

        JTextpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextpesoActionPerformed(evt);
            }
        });
        formularioP.add(JTextpeso);

        btn_inscribir.setText("Inscribir");
        btn_inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inscribirActionPerformed(evt);
            }
        });
        formularioP.add(btn_inscribir);

        jPanel1.add(formularioP, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void JTextcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextcedulaActionPerformed

    private void JTextpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextpesoActionPerformed

    private void btn_inscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inscribirActionPerformed
        String error = "";
        String liga = JComboBoxliga.getSelectedItem().toString();
        if(liga.equals("Seleccionar")){
            error += "Debe buscar y seleccionar una liga\n";
        }
        String cedula = JTextcedula.getText();
        if(cedula.isEmpty()){
            error += "El campo cedula no puede estar vacio\n";
        }
        String nombre = JTextnombre.getText();
        if(nombre.isEmpty()){
            error += "El campo nombre no puede estar vacio\n";
        }
        String apellido = JTextapellido.getText();
        if(apellido.isEmpty()){
            error += "El campo apellido no puede estar vacio\n";
        }
        String fechaNacimiento = ((JTextField)JDatefechanacimiento.getDateEditor().getUiComponent()).getText();
        if(fechaNacimiento.isEmpty()){
            error += "Debe ingresar una fecha de nacimiento\n";
        }
        String fechaIngreso = ((JTextField)JDatefechaingreso.getDateEditor().getUiComponent()).getText();
        if(fechaIngreso.isEmpty()){
            error += "Debe ingresar una fecha de ingreso\n";
        }
        String nacionalidad = JTextnacionalidad.getText();
        if(nacionalidad.isEmpty()){
            error += "El campo nacionalidad no puede estar vacio\n";
        }
        float peso = 0;
        try {
            peso = Float.parseFloat(JTextpeso.getText());
        } catch (NumberFormatException e){
            error += "El campo peso debe ser un valor numerico\n";
        }
        if(!error.isEmpty()){
            JOptionPane.showMessageDialog(null, error, "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String query = "insert into PRACTICANTE(numero_cedula, nombre, apellido, fecha_nacimiento, fecha_ingreso, nacionalidad, peso, personeria_juridica_liga) values (?,?,?,?,?,?,?,?)";
        Practicante practicante = new Practicante(cedula, nombre, apellido, fechaNacimiento, fechaIngreso, nacionalidad, peso, liga);
        try{
            PreparedStatement ps = Principal.db.prepareStatement(query);
            ps.setString(1, practicante.getCedula());
            ps.setString(2, practicante.getNombre());
            ps.setString(3, practicante.getApellido());
            ps.setString(4, practicante.getFechaNacimiento());
            ps.setString(5, practicante.getFechaIngreso());
            ps.setString(6, practicante.getNacionalidad());
            ps.setFloat(7, practicante.getPeso());
            ps.setString(8, practicante.getPersoneria_juridica_liga());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Practicante inscrito", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_inscribirActionPerformed

    private void JTextligaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextligaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextligaActionPerformed

    private void btn_buscarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarLigaActionPerformed
        String liga = JTextliga.getText();
        
        if(liga.isEmpty()){
            JOptionPane.showMessageDialog(null, "El campo seleccione liga no puede estar vacio", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JComboBoxliga.removeAllItems();
        Pattern pattern = Pattern.compile(liga, Pattern.CASE_INSENSITIVE);
        String query = "select personeria_juridica from LIGA";
        try{
            PreparedStatement ps = Principal.db.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Matcher matcher = pattern.matcher(rs.getString("personeria_juridica"));
                if(matcher.find()){
                    JComboBoxliga.addItem(rs.getString("personeria_juridica"));
                }
            }
            if(JComboBoxliga.getItemCount() == 0){
                JOptionPane.showMessageDialog(null, "No se encontro ninguna liga", "ERROR", JOptionPane.ERROR_MESSAGE);
                JComboBoxliga.addItem("Seleccionar");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_buscarLigaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboBoxliga;
    private com.toedter.calendar.JDateChooser JDatefechaingreso;
    private com.toedter.calendar.JDateChooser JDatefechanacimiento;
    private javax.swing.JTextField JTextapellido;
    private javax.swing.JTextField JTextcedula;
    private javax.swing.JTextField JTextliga;
    private javax.swing.JTextField JTextnacionalidad;
    private javax.swing.JTextField JTextnombre;
    private javax.swing.JTextField JTextpeso;
    private javax.swing.JButton btn_buscarLiga;
    private javax.swing.JButton btn_inscribir;
    private javax.swing.JPanel formularioP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
