/*
 * Interfaz creada por: Juan José Saavedra Realpe (2210120)
 */
package interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author ether
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form PRINCIPAL
     */
    protected static Connection db = null;
    protected static String estadoDB = null;
    public Principal() {
        initComponents();
/*Esto basicamente hace que lo primero que veas sea el apartado de crear una liga*/    
        BaseDatos BD = new BaseDatos();
        ShowPanel(BD);
        setLocationRelativeTo(null);
        Thread hilo = new Thread(runnable);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        unEspacio = new javax.swing.JLabel();
        diezEspacios = new javax.swing.JLabel();
        diezEspacios2 = new javax.swing.JLabel();
        unEspacio2 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btn_BaseDatos = new javax.swing.JButton();
        btn_crearLiga = new javax.swing.JButton();
        btn_inscribirParticipante = new javax.swing.JButton();
        btn_actualizarExamen = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JButtonestado = new javax.swing.JButton();
        JLabelestado = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 51));

        panel_menu.setBackground(new java.awt.Color(153, 51, 0));
        panel_menu.setLayout(new java.awt.GridLayout(2, 1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FCTDOS.png"))); // NOI18N
        panel_menu.add(logo);

        panelLogin.setBackground(new java.awt.Color(153, 51, 0));
        panelLogin.setLayout(new java.awt.BorderLayout());

        unEspacio.setBackground(new java.awt.Color(255, 255, 255));
        unEspacio.setText(" ");
        panelLogin.add(unEspacio, java.awt.BorderLayout.PAGE_START);

        diezEspacios.setBackground(new java.awt.Color(255, 204, 204));
        diezEspacios.setText("          ");
        panelLogin.add(diezEspacios, java.awt.BorderLayout.LINE_END);

        diezEspacios2.setBackground(new java.awt.Color(255, 204, 204));
        diezEspacios2.setText("          ");
        panelLogin.add(diezEspacios2, java.awt.BorderLayout.LINE_START);

        unEspacio2.setBackground(new java.awt.Color(255, 204, 204));
        unEspacio2.setText(" ");
        panelLogin.add(unEspacio2, java.awt.BorderLayout.PAGE_END);

        panelBotones.setBackground(new java.awt.Color(153, 51, 0));
        panelBotones.setLayout(new java.awt.GridLayout(6, 2));

        btn_BaseDatos.setText("Base de Datos");
        btn_BaseDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BaseDatosActionPerformed(evt);
            }
        });
        panelBotones.add(btn_BaseDatos);

        btn_crearLiga.setText("Crear Liga");
        btn_crearLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearLigaActionPerformed(evt);
            }
        });
        panelBotones.add(btn_crearLiga);

        btn_inscribirParticipante.setText("Inscribir Participante");
        btn_inscribirParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inscribirParticipanteActionPerformed(evt);
            }
        });
        panelBotones.add(btn_inscribirParticipante);

        btn_actualizarExamen.setText("Actualizar Examen");
        btn_actualizarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarExamenActionPerformed(evt);
            }
        });
        panelBotones.add(btn_actualizarExamen);

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        panelBotones.add(btn_consultar);

        jPanel1.setBackground(new java.awt.Color(153, 51, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Base de Datos:");

        JButtonestado.setBackground(new java.awt.Color(255, 0, 0));
        JButtonestado.setForeground(new java.awt.Color(255, 0, 0));
        JButtonestado.setText(" ");

        JLabelestado.setForeground(new java.awt.Color(255, 255, 255));
        JLabelestado.setText("Desconectada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(JButtonestado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelestado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelestado)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JButtonestado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBotones.add(jPanel1);

        panelLogin.add(panelBotones, java.awt.BorderLayout.CENTER);

        panel_menu.add(panelLogin);

        getContentPane().add(panel_menu, java.awt.BorderLayout.LINE_START);

        contenedor.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Runnable runnable = new Runnable(){ 
    public void run(){
        
        while(true){
            try{
                Thread.sleep(5000);
                if(estadoDB == "Desconectada" || estadoDB == null){
                JLabelestado.setText("Desconectada");
                JButtonestado.setBackground(Color.red);
                } else{
                JLabelestado.setText("Conectada");
                JButtonestado.setBackground(Color.green);
                }  
            }catch (InterruptedException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        }
    };
    
/********************************BOTONES DEL MENU*****************************/
    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        // TODO add your handling code here:
        Consultar consu = new Consultar();
        ShowPanel(consu);
//        String query = "select * from prueba";
//        try{
//            PreparedStatement ps = db.prepareStatement(query);
//            ResultSet rs = ps.executeQuery();
//            System.out.println(rs);
//            while(rs.next()){
//                System.out.println(rs.getString("nombre"));
//                System.out.println(rs.getString("numero"));
//                System.out.println(rs.getString("fecha"));
//            }
//        } catch (SQLException ex) {
//            System.out.println("error: " + ex.getMessage());
//        }
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_inscribirParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inscribirParticipanteActionPerformed
        InscribirPracticante IP = new InscribirPracticante();
        ShowPanel(IP);
    }//GEN-LAST:event_btn_inscribirParticipanteActionPerformed

    private void btn_actualizarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarExamenActionPerformed
        // TODO add your handling code here:
        ActualizarExamen actuExam = new ActualizarExamen();
        ShowPanel(actuExam);
    }//GEN-LAST:event_btn_actualizarExamenActionPerformed

    private void btn_crearLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearLigaActionPerformed
        // TODO add your handling code here:
        CrearLiga cl = new CrearLiga();
        ShowPanel(cl);
    }//GEN-LAST:event_btn_crearLigaActionPerformed

    private void btn_BaseDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BaseDatosActionPerformed
        // TODO add your handling code here:
        BaseDatos BD = new BaseDatos();
        ShowPanel(BD);
    }//GEN-LAST:event_btn_BaseDatosActionPerformed
/******************************FIN DE BOTONES**********************************/
    
    
/*******************METODO QUE PERMITE CAMBIAR LOS PANELES*********************/
    private void ShowPanel(JPanel p) {
        p.setSize(573, 728);
        p.setLocation(0, 0);
        
        contenedor.removeAll();
        contenedor.add(p, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }
/****************FIN DE METODO QUE PERMITE CAMBIAR LOS PANELES*****************/
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonestado;
    private javax.swing.JLabel JLabelestado;
    private javax.swing.JButton btn_BaseDatos;
    private javax.swing.JButton btn_actualizarExamen;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_crearLiga;
    private javax.swing.JButton btn_inscribirParticipante;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel diezEspacios;
    private javax.swing.JLabel diezEspacios2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JLabel unEspacio;
    private javax.swing.JLabel unEspacio2;
    // End of variables declaration//GEN-END:variables
}
